GET http://localhost:3000/apartments

###

POST http://localhost:3000/apartments
Content-Type: application/json

{
    "number": 2,
    "cost": 200000
}

###

DELETE http://localhost:3000/apartments

###

POST http://localhost:3000/apartments/sendMail