GET http://localhost:3000/apartments

###

GET http://localhost:3000/apartments/62c7d2db3d728be1a773ccb5

### Get first match by number 

GET http://localhost:3000/apartments/num/2

### 

POST http://localhost:3000/apartments
Content-Type: application/json

{
    "number": 2,
    "cost": 200000
}

###

DELETE http://localhost:3000/apartments

###

POST http://localhost:3000/apartments/sendMail/giladij@outlook.com/yo/yoyo